[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
name = "truenas"
version = "0.0.1"
edition = "2024"

[workspace.dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = ["full"] }
tokio-tungstenite = "0.27.0"
thiserror = { version = "2.0.16" }
futures = { version = "0.3.31" }
uuid = { version = "1.18.0", features = ["v4"] }
futures-util = { version = "0.3.31" }
